title: "Brad's blog"
description: "A Markdown-powered blog"
baseurl: "" # Leave blank unless your site is at a subpath
url: "https://bradewin.github.io" # Replace with your real blog URL

remote_theme: jekyll/minima@master

markdown: kramdown
highlighter: rouge

# Include any extra files/folders
include:
  - _pages

# Exclude these from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
